# Generated by Django 5.0.2 on 2024-02-06 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sandels', 'sandels'), ('sneakers', 'sneakers'), ('boots', 'boots'), ('formal shoe', 'formal shoe'), ('trainers', 'trainers'), ('slip-ons', 'slip-ons')], max_length=11)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
